flaskr/models.py
#models.py
from flaskr import db,ma
from datetime import datetime
from flask_login import UserMixin
from flask_bcrypt import generate_password_hash,check_password_hash

#-------ユーザ情報テーブル-------#
class User(UserMixin,db.Model):
    #テーブル定義
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(64),unique=True,index=True,nullable=False)
    password = db.Column(db.String(64),nullable=False)
    create_at=db.Column(db.DateTime,default=datetime.now)
    update_at=db.Column(db.DateTime,default=datetime.now)

    #初期化
    def __init__(self,username,password):
        self.username = username
        self.password = generate_password_hash(password)

    #入力されたパスワードが登録されたパスワードと一致しているか
    def validate_password(self,password):
        return check_password_hash(self.password,password)

    #ユーザ追加
    def add_user(self):
        with db.session.begin(subtransactions=True):
            db.session.add(self)
        db.session.commit()

    #usernameからレコードの取り出し
    @classmethod
    def select_by_username(cls,username):
        return cls.query.filter_by(username=username).first()
#-------ユーザ情報テーブル-------#

#-------ドリンク情報を保管するテーブル-------#
class DrinkList(db.Model):
    __tablename__ = 'drinkList'
    id = db.Column(db.Integer,primary_key=True)
    productName = db.Column(db.String(64),index=True)
    jancode = db.Column(db.String(64))
    create_at=db.Column(db.DateTime,default=datetime.now)

    def __init__(self,productName,jancode):
        self.productName=productName
        self.jancode=jancode

class DrinkSchema(ma.Schema):
    class Meta:
        fields = ("drink_id","productName","jancode","create_at")
#-------ドリンク情報を保管するテーブル-------#

drink_schema = DrinkSchema()

flaskr/forms.py
#forms.py
from wtforms import Form
from wtforms.fields import (
    StringField,SubmitField,HiddenField,IntegerField,PasswordField
)
from wtforms.validators import DataRequired,NumberRange,EqualTo
from wtforms import ValidationError
from flaskr.models import User

#-----ログイン・登録管理フォーム----#
#ログイン
class LoginForm(Form):
    username = StringField(
        'ユーザ名',validators=[DataRequired()]
    )
    password = PasswordField(
        'パスワード',validators=[DataRequired()]
    )
    submit = SubmitField('ログイン')

#登録
class RegisterForm(Form):
    username = StringField(
        'ユーザ名',validators=[DataRequired()]
    )
    password = PasswordField(
        'パスワード',validators=[DataRequired(),EqualTo('confirm_password',message='パスワードが一致しません。もう一度確認してください')]
    )
    confirm_password = PasswordField(
        'パスワード確認',validators=[DataRequired()]
    )
    submit = SubmitField('登録')

    #ユーザ名がすでに登録されている場合のエラー
    def validate_username(self, field):
        if User.select_by_username(field.data):
            raise ValidationError('そのユーザ名は使われています')
#-----ログイン・ログアウト管理フォーム----#

#----------ドリンクの管理フォーム---------#
#追加
class RegisterDrink(Form):
    drinkname = StringField(
        '名称:',validators=[DataRequired()]
    )
    quantity = IntegerField(
        '個数:',validators=[DataRequired(),NumberRange(0,25,'0~24以内で入力してください')]
    )
    submit = SubmitField('追加する')

#削除
class DeleteDrink(Form):
    id=HiddenField()
    submit = SubmitField('削除')
#----------ドリンクの管理フォーム----------#

flaskr/__init__.py
#__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_marshmallow import Marshmallow
from flask_login import LoginManager

basedir = os.path.abspath(os.path.dirname(__name__))
db = SQLAlchemy()
ma = Marshmallow()
migrate = Migrate()
login_manager = LoginManager() #ログインマネージャ

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = b'\xa9\xfb\x81l\x8c\xe9\xa7\xcb\xb80\xcb02\xea\x9b\xb6'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir,'data.sqlite')
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    db.init_app(app)
    login_manager.init_app(app)
    migrate.init_app(app, db)
    from flaskr.views import bp
    app.register_blueprint(bp)
    from flaskr.views import bp
    app.register_blueprint(bp)
    return app

flaskr/views.py
#views.py
from flask import request,render_template,redirect,url_for,flash,Blueprint
from flaskr import db,login_manager
from flaskr.forms import RegisterDrink,DeleteDrink,LoginForm,RegisterForm
from flaskr.models import DrinkList,drink_schema,User
from flask_login import login_required,login_user,logout_user

bp = Blueprint('app', __name__, url_prefix='')


#---------ホームページ---------#
@bp.route('/')
def home():
    return render_template('home.html')
#---------ホームページ---------#


#-----------ログイン処理設定---------#
login_manager.login_view = 'app.login'
login_manager.login_message = ''
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)
#----------ログイン処理設定----------#


#----------ログイン・ログアウト・登録----------#
@bp.route('/login',methods=['GET','POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.select_by_username(form.username.data)
        if user and user.validate_password(form.password.data):
            login_user(user,remember=True)
            next = request.args.get('next')
            if not next:
                next = url_for('app.drink_list')
            return redirect(next)
    return render_template('login.html',form=form)

@bp.route('/register',methods=['GET','POST'])
def register():
    form = RegisterForm(request.form)
    if request.method=='POST' and form.validate():
        user = User(
            username = form.username.data,
            password = form.password.data
        )
        user.add_user()
        return redirect(url_for('app.login'))
    return render_template('register.html',form=form)

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('app.home'))

#ログインしているユーザの情報を表示
@bp.route('/user')
@login_required
def user_info():
    return render_template('user.html')
#-----------ログイン・ログアウト・登録----------#


#---------ドリンク関連---------#
#飲料一覧ページ
@bp.route('/drink_list')
@login_required
def drink_list():
    drinks = DrinkList.query.all()
    delete_form = DeleteDrink(request.form)
    return render_template('drink_list.html',delete_form=delete_form,drinks=drinks)

#飲料追加ページ
@bp.route('/add_drink',methods=['GET','POST'])
def add_drink():
    form = RegisterDrink(request.form)
    if request.method=='POST' and form.validate():
        for regist in range(form.quantity.data):
            productName=form.drinkname.data
            jancode=''
            with db.session.begin(subtransactions=True):
                new_drink = DrinkList(productName,jancode)
                db.session.add(new_drink)
            db.session.commit()
        return redirect(url_for('app.drink_list'))
    return render_template('add_drink.html',form=form)

#飲料削除動作
@bp.route('/delete_drink',methods=['GET','POST'])
def delete_drink():
    form = DeleteDrink(request.form)
    if request.method=='POST' and form.validate():
        print(form.id.data)
        with db.session.begin(subtransactions=True):
            id=form.id.data
            drink=DrinkList.query.get(id)
            db.session.delete(drink)
        db.session.commit()
        return redirect(url_for('app.drink_list'))
    return redirect(url_for('app.drink_list'))
#---------ドリンク関連---------#


#---------API---------#
@bp.route('/api/adddrink',methods=["POST"])
def api_post():
    if not "productName" and not "jancode" in request.json:
      return "error"
    item = DrinkList(productName=request.json["productName"],jancode=request.json["jancode"])
    db.session.add(item)
    db.session.commit()
    return drink_schema.jsonify(item)
#---------API---------#

flaskr/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>{{ field.label }}
    <dd>{{ field(**kwargs)| safe }}
        {% if field.errors %}
        <ul class="errors">
            {% for error in field.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </dd>
</dt>
{% endmacro %}

flaskr/templates/add_drink.html
{%extends 'base.html'%} {%block content%}

<div>
  <!-- <header class="site-header">
    <form class="add_form" method="POST">
      {{form.submit(class_="add_button")}}
    </form>
  </header> -->
    <form method="POST">
        <header class="site-header">{{form.submit(class_="add_button")}}</header>
        <div class="add-form">
      <div class="namelabel">{{form.drinkname.label}}</div>
      <div class="formbutton">{{form.drinkname(class_="formbuttons")}}</div>
      <div class="quantitylabel">{{form.quantity.label}}</div>
      <div class="formbutton">{{form.quantity(class_="formbuttons num")}}</div>
    </form>
  </div>
</div>
{%endblock%}

<div class="namelabel"></div>
<div class="quantitylabel"></div>
<div class="formbutton"></div>

flaskr/templates/base.html
<!DOCTYPE html>
<html lag="ja">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width,initial-scale=1.0,minimum-scale=1.0"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Noto+Sans+JP:wght@400;700&display=swap"
      rel="stylesheet"
    />
    <title></title>
    <link rel="stylesheet" href="static/css/style.css" />
  </head>
  <body bgcolor="#fef2e4">
    {%block content%} {%endblock%}
  </body>
</html>

flaskr/templates/drink_list.html
{%extends 'base.html'%} {%block content%}
<header class="site-header">
  <h1 class="site-title">Takahashi Drink App</h1>
  <a href="{{url_for('app.user_info')}}">{{current_user.username}}</a>
</header>

<div class="drink_list">
    {%for drink in drinks%}
        <div class="drink-column">
            <div class="drink_name_box">
                <span class="drink_name">
                    {{drink.productName}}
                </span>
            </div>
            <div class="drink_delete">
                <form class="delete" method="POST" action="{{url_for('app.delete_drink')}}">
                    {{delete_form.csrf_token}} {{delete_form.id(value=drink.id)}}
                    {{delete_form.submit(class_="delete-button")}}
                </form>
            </div>
        </div>
    {%endfor%}
  <input class="btn btn--orange btn--circle btn--circle-a btn--shadow" type="button" onclick="location.href='{{url_for('app.add_drink')}}'" value="Add Drink"></button>
</div>
{%endblock%}

flaskr/templates/drinks.html
{%extends 'base.html'%}
{%block content%}
<a href="{{url_for('add_drink')}}">ドリンクの追加</a>
<div>
    <h1>ドリンク一覧</h1>
    <table>
        <tr>
            <th>商品名</th>
            <th>削除</th>
        </tr>
        {%for drinks in drink%}
        <tr>
            <td>{{drink.productName}}</td>
            <td>
                <form method="POST" action="{{url_for('delete_drink')}}">
                    {{delete_form.csrf_token}}
                    {{delete_form.id(value=drink.id)}}
                    {{delte_form.submit()}}
            </td>
        </tr>
        {%endfor%}
    </table>
</div>
{%endblock%}

flaskr/templates/home.html
{%extends 'base.html'%}
{%block content%}
<h1>TakahashiDrinkApp</h1>
<a href="{{url_for('app.drink_list')}}">ドリンク一覧</a>
{%endblock%}

flaskr/templates/login.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block content %}
{% for message in get_flashed_messages() %} {# リダイレクトした際のメッセージ#}
{{ message }}
{% endfor %}
ログイン
<form method="POST">
    {{form.csrf_token}}
    {{render_field(form.username)}}
    {{render_field(form.password)}}
    {{form.submit()}}
</form>

または
<a href="{{url_for('app.register')}}">新規登録</a>
{% endblock %}

flaskr/templates/register.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block content %}
<h1>ユーザ情報登録画面</h1>
<form method="POST">
    {{form.csrf_token}}
    {{render_field(form.username)}}
    {{render_field(form.password)}}
    {{render_field(form.confirm_password)}}
    {{form.submit()}}
</form>
{% endblock %}

flaskr/templates/user.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block content %}
<p>ユーザ名:{{current_user.username}}</p>
<a href="{{url_for('app.logout')}}">ログアウト</a>
{% endblock %}